ubersan/pylic

- .github/workflows/integration-tests.yml
- .github/workflows/unit-tests.yml
- README.md
- poetry.lock
- pylic/pylic.py
- pyproject.toml
- tests/test_pylic.py
- tests/test_tomls/unknown_license_allowed.toml
> #7: Update variable naming

- pyproject.toml
- setup.py
> #13: Make package callable on command line.

- .gitignore
- Dockerfile
- README.md
- pyproject.toml
- scripts/publish_new_docker.sh
> #3: Add Dockerfile.

- Dockerfile
- README.md
- scripts/publish_new_docker.sh
> #17: Remove docker stuff.

- .github/workflows/python-version-integration-tests.yml
- pylic/pylic.py
- pyproject.toml
- tests/test_pylic.py
> #19: Warnings as errors

- .github/workflows/python-version-integration-tests.yml
> #24: Integration tests actually test version which is not yet released.

- .github/workflows/python-version-integration-tests.yml
> #24: Remove unnencessary python version print and rephrase job description.

- pylic/pylic.py
- pyproject.toml
- tests/test_pylic.py
> #27: List packages as unsafe it license is unknown.

- README.md
> #29: Improve readme with usage example and better explanation.

- pylic/pylic.py
- pyproject.toml
- tests/test_pylic.py
> #30: Use 2 spaces instead 1 tab. Looks nicer on the shell where tabs are 8 spaces.

- pylic/pylic.py
- tests/test_pylic.py
> #33: Show package versions when showing an error.

- pylic/pylic.py
- pyproject.toml
- setup.cfg
- tests/test_pylic.py
> Enforce stricter mypy rules and fix all errors.

- poetry.lock
- pyproject.toml
> #38: Release v1.2.0 with package versions in outputs.

- README.md
> #33: Update usage example with the new output displaying the package versions.

- README.md
- poetry.lock
> #33 fix readme

- poetry.lock
- pyproject.toml
> #33 update poetry

- README.md
> explicate only installed packages are checked.

- pylic/__version__.py
- pylic/cli/app.py
- pylic/cli/commands/check.py
- pylic/cli/commands/help.py
- pylic/cli/commands/list.py
- pyproject.toml
- tests/unit_tests/cli/app_test.py
same style, but custom content. Also the return code is 1.
> Provide custom help command

- README.md
- poetry.lock
- pylic/__version__.py
- pylic/cli/commands/check.py
- pylic/cli/commands/command.py
- pylic/cli/commands/help.py
- pylic/cli/commands/list.py
- pylic/cli/commands/version.py
- pylic/cli/console_reader.py
- pylic/cli/console_writer.py
- pyproject.toml
- tests/integration_tests/full_app_test.py
- tests/integration_tests/test_tomls/unnecessary_unsafe_package_and_safe_license.toml
- tests/unit_tests/cli/commands/check_test.py
- tests/unit_tests/cli/console_reader_test.py
> Add check command options to allow declaring extra licenses or packages

- .pre-commit-hooks.yaml
> Provide pre-commit hook.

- README.md
> Add section about pre-commit to README.

- pylic/cli/commands/check.py
- pyproject.toml
- tests/integration_tests/full_app_test.py
> fix typo in check-format task
